# frozen_string_literal: true

source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'
target 'WPMediaPicker' do
  pod 'WPMediaPicker', path: '../'

  target 'Tests' do
    inherit! :search_paths
  end
end
