osx_image: xcode7.3
sudo: false
language: objective-c
script:
- set -o pipefail && xcodebuild build -workspace MediaPicker.xcworkspace -scheme WPMediaPicker -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
